# Generated by Django 3.2.4 on 2021-07-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='added_by',
            new_name='created_by',
        ),
    ]
